
version: '3.2'

services:



  zoo:
    # build from Dockerfile
    image: confluentinc/cp-zookeeper:latest
    container_name: zoo
    restart: unless-stopped
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: server.1=zoo:2888:3888
    volumes:
      - ./bootcamp/zoo/data:/data
      - ./bootcamp/zoo/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kaf
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2183"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./bootcamp/kafka/data:/lib/kafka/data
    depends_on:
      - zoo
      

  db:
    image: 'postgres:13.1-alpine'
    container_name: kafkadb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=kafkademo
  app:
    # build from Dockerfile
    container_name: kafkaapp
    image: kafkaapp
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://db:5432/kafkademo
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=123456
      - GMAIL_USER=jaymishptl@gmail.com
      - GMAIL_PASSWORD=dubxclrrxluaiimd

  
