version: '3.1'

services:
  app:
    # build from Dockerfile
    container_name: weather-app
    image: weather-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://db:5432/weather
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=123456

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=weather
