
version: '3.2'

services:

  db:
    image: 'postgres:13.1-alpine'
    container_name: kafkadb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=kafkademo
  app:
    # build from Dockerfile
    container_name: kafkaapp
    image: kafkaapp
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://db:5432/kafkademo
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=123456

  
